- name: Configure vm for pythian submission
  hosts: pythian_vm
  sudo: True
  tasks:
     - name: Test if the VM server is alive
       action: ping
       
     - apt: name={{ item }} state=latest update_cache=yes
       with_items:
        - apache2
        - git
        - mysql-server
        - mysql-client
     - name: creating a folder code in /opt/code
       file:
         path: /opt/code
         state: directory
         owner: root
         group: pythian
         mode: 0750

     - name: Clone private repo into /opt/code
       git:
         repo: https://github.com/mininet/mininet
         version: master
         dest: /opt/code
         accept_hostkey: yes
       # ssh-agent preventing key to pass through remote sudo commands
       become: yes
     - group:
         name: pythian
         state: present
